{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2025-22153",
		"assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
		"assignerShortName": "GitHub_M",
		"state": "PUBLISHED",
		"datePublished": "2025-01-23T17:34:27.056Z",
		"dateUpdated": "2025-02-12T20:41:29.946Z",
		"dateReserved": "2024-12-30T03:00:33.655Z"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "a0819718-46f1-4df5-94e2-005712e83aaa",
				"shortName": "GitHub_M",
				"dateUpdated": "2025-01-23T17:34:27.056Z"
			},
			"title": "try/except* clauses could allow bypass RestrictedPython via type confusion bug in the CPython interpreter",
			"descriptions": [
				{
					"lang": "en",
					"value": "RestrictedPython is a tool that helps to define a subset of the Python language which allows to provide a program input into a trusted environment. Via a type confusion bug in versions of the CPython interpreter starting in 3.11 and prior to 3.13.2 when using `try/except*`, RestrictedPython starting in version 6.0 and prior to version 8.0 could be bypassed. The issue is patched in version 8.0 of RestrictedPython by removing support for `try/except*` clauses. No known workarounds are available."
				}
			],
			"affected": [
				{
					"vendor": "zopefoundation",
					"product": "RestrictedPython",
					"versions": [
						{
							"status": "affected",
							"version": ">= 6.0, < 8.0"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-843: Access of Resource Using Incompatible Type ('Type Confusion')",
							"cweId": "CWE-843"
						}
					]
				}
			],
			"metrics": [
				{
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:C/C:H/I:H/A:L",
						"attackVector": "NETWORK",
						"attackComplexity": "HIGH",
						"privilegesRequired": "HIGH",
						"userInteraction": "NONE",
						"scope": "CHANGED",
						"confidentialityImpact": "HIGH",
						"integrityImpact": "HIGH",
						"availabilityImpact": "LOW",
						"baseScore": 7.9,
						"baseSeverity": "HIGH"
					}
				}
			],
			"references": [
				{
					"name": "https://github.com/zopefoundation/RestrictedPython/security/advisories/GHSA-gmj9-h825-chq2",
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/zopefoundation/RestrictedPython/security/advisories/GHSA-gmj9-h825-chq2"
				},
				{
					"name": "https://github.com/zopefoundation/RestrictedPython/commit/48a92c5bb617a647cffd0dadd4d5cfe626bcdb2f",
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/zopefoundation/RestrictedPython/commit/48a92c5bb617a647cffd0dadd4d5cfe626bcdb2f"
				}
			],
			"source": {
				"advisory": "GHSA-gmj9-h825-chq2",
				"discovery": "UNKNOWN"
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
					"shortName": "CISA-ADP",
					"dateUpdated": "2025-02-12T20:41:29.946Z"
				},
				"title": "CISA ADP Vulnrichment",
				"metrics": [
					{
						"other": {
							"type": "ssvc",
							"content": {
								"id": "CVE-2025-22153",
								"options": [
									{
										"Exploitation": "none"
									},
									{
										"Automatable": "no"
									},
									{
										"Technical Impact": "total"
									}
								],
								"role": "CISA Coordinator",
								"timestamp": "2025-01-23T18:59:04.049782Z",
								"version": "2.0.3"
							}
						}
					}
				]
			}
		]
	}
}
