{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2023-23969",
		"assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
		"assignerShortName": "mitre",
		"state": "PUBLISHED",
		"datePublished": "2023-02-01T00:00:00.000Z",
		"dateUpdated": "2025-02-13T16:44:12.812Z",
		"dateReserved": "2023-01-20T00:00:00.000Z"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
				"shortName": "mitre",
				"dateUpdated": "2023-04-28T03:06:12.957Z"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "In Django 3.2 before 3.2.17, 4.0 before 4.0.9, and 4.1 before 4.1.6, the parsed values of Accept-Language headers are cached in order to avoid repetitive parsing. This leads to a potential denial-of-service vector via excessive memory usage if the raw value of Accept-Language headers is very large."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"url": "https://groups.google.com/forum/#%21forum/django-announce"
				},
				{
					"url": "https://docs.djangoproject.com/en/4.1/releases/security/"
				},
				{
					"url": "https://www.djangoproject.com/weblog/2023/feb/01/security-releases/"
				},
				{
					"name": "[debian-lts-announce] 20230201 [SECURITY] [DLA 3306-1] python-django security update",
					"tags": [
						"mailing-list"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2023/02/msg00000.html"
				},
				{
					"url": "https://security.netapp.com/advisory/ntap-20230302-0007/"
				},
				{
					"name": "FEDORA-2023-8fed428c5e",
					"tags": [
						"vendor-advisory"
					],
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"
				},
				{
					"name": "FEDORA-2023-a53ab7c969",
					"tags": [
						"vendor-advisory"
					],
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"
				}
			]
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-02T10:49:08.226Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_transferred"
						],
						"url": "https://groups.google.com/forum/#%21forum/django-announce"
					},
					{
						"tags": [
							"x_transferred"
						],
						"url": "https://docs.djangoproject.com/en/4.1/releases/security/"
					},
					{
						"tags": [
							"x_transferred"
						],
						"url": "https://www.djangoproject.com/weblog/2023/feb/01/security-releases/"
					},
					{
						"name": "[debian-lts-announce] 20230201 [SECURITY] [DLA 3306-1] python-django security update",
						"tags": [
							"mailing-list",
							"x_transferred"
						],
						"url": "https://lists.debian.org/debian-lts-announce/2023/02/msg00000.html"
					},
					{
						"tags": [
							"x_transferred"
						],
						"url": "https://security.netapp.com/advisory/ntap-20230302-0007/"
					},
					{
						"name": "FEDORA-2023-8fed428c5e",
						"tags": [
							"vendor-advisory",
							"x_transferred"
						],
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"
					},
					{
						"name": "FEDORA-2023-a53ab7c969",
						"tags": [
							"vendor-advisory",
							"x_transferred"
						],
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"
					}
				]
			}
		]
	}
}
