{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2018-18074",
		"assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
		"assignerShortName": "mitre",
		"state": "PUBLISHED",
		"datePublished": "2018-10-09T15:00:00",
		"dateUpdated": "2024-08-05T11:01:14.951Z",
		"dateReserved": "2018-10-09T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
				"shortName": "mitre",
				"dateUpdated": "2022-07-22T17:57:42"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "The Requests package before 2.20.0 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"name": "USN-3790-1",
					"tags": [
						"vendor-advisory",
						"x_refsource_UBUNTU"
					],
					"url": "https://usn.ubuntu.com/3790-1/"
				},
				{
					"name": "USN-3790-2",
					"tags": [
						"vendor-advisory",
						"x_refsource_UBUNTU"
					],
					"url": "https://usn.ubuntu.com/3790-2/"
				},
				{
					"name": "openSUSE-SU-2019:1754",
					"tags": [
						"vendor-advisory",
						"x_refsource_SUSE"
					],
					"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html"
				},
				{
					"name": "RHSA-2019:2035",
					"tags": [
						"vendor-advisory",
						"x_refsource_REDHAT"
					],
					"url": "https://access.redhat.com/errata/RHSA-2019:2035"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://www.oracle.com/security-alerts/cpujul2022.html"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "http://docs.python-requests.org/en/master/community/updates/#release-and-version-history"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://bugs.debian.org/910766"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/requests/requests/issues/4716"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/requests/requests/pull/4718"
				}
			],
			"datePublic": "2018-10-09T00:00:00",
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "cve@mitre.org",
					"ID": "CVE-2018-18074",
					"STATE": "PUBLIC"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "n/a",
											"version": {
												"version_data": [
													{
														"version_value": "n/a"
													}
												]
											}
										}
									]
								},
								"vendor_name": "n/a"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "The Requests package before 2.20.0 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network."
						}
					]
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "n/a"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "USN-3790-1",
							"refsource": "UBUNTU",
							"url": "https://usn.ubuntu.com/3790-1/"
						},
						{
							"name": "USN-3790-2",
							"refsource": "UBUNTU",
							"url": "https://usn.ubuntu.com/3790-2/"
						},
						{
							"name": "openSUSE-SU-2019:1754",
							"refsource": "SUSE",
							"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html"
						},
						{
							"name": "RHSA-2019:2035",
							"refsource": "REDHAT",
							"url": "https://access.redhat.com/errata/RHSA-2019:2035"
						},
						{
							"name": "https://www.oracle.com/security-alerts/cpujul2022.html",
							"refsource": "MISC",
							"url": "https://www.oracle.com/security-alerts/cpujul2022.html"
						},
						{
							"name": "http://docs.python-requests.org/en/master/community/updates/#release-and-version-history",
							"refsource": "CONFIRM",
							"url": "http://docs.python-requests.org/en/master/community/updates/#release-and-version-history"
						},
						{
							"name": "https://bugs.debian.org/910766",
							"refsource": "MISC",
							"url": "https://bugs.debian.org/910766"
						},
						{
							"name": "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff",
							"refsource": "MISC",
							"url": "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff"
						},
						{
							"name": "https://github.com/requests/requests/issues/4716",
							"refsource": "MISC",
							"url": "https://github.com/requests/requests/issues/4716"
						},
						{
							"name": "https://github.com/requests/requests/pull/4718",
							"refsource": "MISC",
							"url": "https://github.com/requests/requests/pull/4718"
						}
					]
				}
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-05T11:01:14.951Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"name": "USN-3790-1",
						"tags": [
							"vendor-advisory",
							"x_refsource_UBUNTU",
							"x_transferred"
						],
						"url": "https://usn.ubuntu.com/3790-1/"
					},
					{
						"name": "USN-3790-2",
						"tags": [
							"vendor-advisory",
							"x_refsource_UBUNTU",
							"x_transferred"
						],
						"url": "https://usn.ubuntu.com/3790-2/"
					},
					{
						"name": "openSUSE-SU-2019:1754",
						"tags": [
							"vendor-advisory",
							"x_refsource_SUSE",
							"x_transferred"
						],
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html"
					},
					{
						"name": "RHSA-2019:2035",
						"tags": [
							"vendor-advisory",
							"x_refsource_REDHAT",
							"x_transferred"
						],
						"url": "https://access.redhat.com/errata/RHSA-2019:2035"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://www.oracle.com/security-alerts/cpujul2022.html"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "http://docs.python-requests.org/en/master/community/updates/#release-and-version-history"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://bugs.debian.org/910766"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://github.com/requests/requests/issues/4716"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://github.com/requests/requests/pull/4718"
					}
				]
			}
		]
	}
}
