{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2015-5159",
		"assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
		"assignerShortName": "redhat",
		"state": "PUBLISHED",
		"datePublished": "2018-10-30T18:00:00",
		"dateUpdated": "2024-08-06T06:32:32.909Z",
		"dateReserved": "2015-07-01T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "53f830b8-0a3f-465b-8143-3b8a9948e749",
				"shortName": "redhat",
				"dateUpdated": "2018-10-30T17:57:01"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "python-kdcproxy before 0.3.2 allows remote attackers to cause a denial of service via a large POST request."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882"
				}
			],
			"datePublic": "2015-07-21T00:00:00"
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-06T06:32:32.909Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882"
					}
				]
			}
		]
	}
}
