{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2020-6937",
		"assignerOrgId": "c9b25dee-ae6d-4083-ba23-638c500cc364",
		"assignerShortName": "Salesforce",
		"state": "PUBLISHED",
		"datePublished": "2020-05-29T21:27:33",
		"dateUpdated": "2024-08-04T09:18:02.520Z",
		"dateReserved": "2020-01-13T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "c9b25dee-ae6d-4083-ba23-638c500cc364",
				"shortName": "Salesforce",
				"dateUpdated": "2020-05-29T21:27:33"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "A Denial of Service vulnerability in MuleSoft Mule CE/EE 3.8.x, 3.9.x, and 4.x released before April 7, 2020, could allow remote attackers to submit data which can lead to resource exhaustion."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "MuleSoft Mule CE/EE",
					"versions": [
						{
							"status": "affected",
							"version": "3.8.x"
						},
						{
							"status": "affected",
							"version": "3.9.x"
						},
						{
							"status": "affected",
							"version": "4.x"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "Denial of Service"
						}
					]
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://help.salesforce.com/articleView?id=000353701&language=en_US&type=1&mode=1"
				}
			],
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "security@salesforce.com",
					"ID": "CVE-2020-6937",
					"STATE": "PUBLIC"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "MuleSoft Mule CE/EE",
											"version": {
												"version_data": [
													{
														"version_value": "3.8.x"
													},
													{
														"version_value": "3.9.x"
													},
													{
														"version_value": "4.x"
													}
												]
											}
										}
									]
								},
								"vendor_name": "n/a"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "A Denial of Service vulnerability in MuleSoft Mule CE/EE 3.8.x, 3.9.x, and 4.x released before April 7, 2020, could allow remote attackers to submit data which can lead to resource exhaustion."
						}
					]
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "Denial of Service"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "https://help.salesforce.com/articleView?id=000353701&language=en_US&type=1&mode=1",
							"refsource": "CONFIRM",
							"url": "https://help.salesforce.com/articleView?id=000353701&language=en_US&type=1&mode=1"
						}
					]
				}
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-04T09:18:02.520Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://help.salesforce.com/articleView?id=000353701&language=en_US&type=1&mode=1"
					}
				]
			}
		]
	}
}
