{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"cveId": "CVE-2022-0718",
		"assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
		"assignerShortName": "redhat",
		"state": "PUBLISHED",
		"datePublished": "2022-08-29T14:03:04",
		"dateUpdated": "2022-09-13T15:06:20",
		"dateReserved": "2022-02-22T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "53f830b8-0a3f-465b-8143-3b8a9948e749",
				"shortName": "redhat",
				"dateUpdated": "2022-09-13T15:06:20"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( \" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "openstack/python-oslo.utils",
					"versions": [
						{
							"status": "affected",
							"version": "Affects all versions, Fixed in 4.10.1, 4.12.1."
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-522 - Insufficiently Protected Credentials",
							"cweId": "CWE-522"
						}
					]
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://bugs.launchpad.net/oslo.utils/+bug/1949623"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://security-tracker.debian.org/tracker/CVE-2022-0718"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://access.redhat.com/security/cve/CVE-2022-0718"
				},
				{
					"name": "[debian-lts-announce] 20220913 [SECURITY] [DLA 3106-1] python-oslo.utils security update",
					"tags": [
						"mailing-list",
						"x_refsource_MLIST"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html"
				}
			]
		}
	}
}
