{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"cveId": "CVE-2022-36027",
		"assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
		"assignerShortName": "GitHub_M",
		"state": "PUBLISHED",
		"datePublished": "2022-09-16T22:50:16",
		"dateUpdated": "2022-09-16T22:50:16",
		"dateReserved": "2022-07-15T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "a0819718-46f1-4df5-94e2-005712e83aaa",
				"shortName": "GitHub_M",
				"dateUpdated": "2022-09-16T22:50:16"
			},
			"title": "Segfault TFLite converter on per-channel quantized transposed convolutions in TensorFlow",
			"descriptions": [
				{
					"lang": "en",
					"value": "TensorFlow is an open source platform for machine learning. When converting transposed convolutions using per-channel weight quantization the converter segfaults and crashes the Python process. We have patched the issue in GitHub commit aa0b852a4588cea4d36b74feb05d93055540b450. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue."
				}
			],
			"affected": [
				{
					"vendor": "tensorflow",
					"product": "tensorflow",
					"versions": [
						{
							"status": "affected",
							"version": "< 2.7.2"
						},
						{
							"status": "affected",
							"version": ">= 2.8.0, < 2.8.1"
						},
						{
							"status": "affected",
							"version": ">= 2.9.0, < 2.9.1"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-20: Improper Input Validation",
							"cweId": "CWE-20"
						}
					]
				}
			],
			"metrics": [
				{
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"attackVector": "NETWORK",
						"attackComplexity": "HIGH",
						"privilegesRequired": "NONE",
						"userInteraction": "NONE",
						"scope": "UNCHANGED",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"availabilityImpact": "HIGH",
						"baseScore": 5.9,
						"baseSeverity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-79h2-q768-fpxr"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/tensorflow/tensorflow/issues/53767"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/tensorflow/tensorflow/commit/aa0b852a4588cea4d36b74feb05d93055540b450"
				}
			],
			"source": {
				"advisory": "GHSA-79h2-q768-fpxr",
				"discovery": "UNKNOWN"
			},
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "security-advisories@github.com",
					"ID": "CVE-2022-36027",
					"STATE": "PUBLIC",
					"TITLE": "Segfault TFLite converter on per-channel quantized transposed convolutions in TensorFlow"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "tensorflow",
											"version": {
												"version_data": [
													{
														"version_value": "< 2.7.2"
													},
													{
														"version_value": ">= 2.8.0, < 2.8.1"
													},
													{
														"version_value": ">= 2.9.0, < 2.9.1"
													}
												]
											}
										}
									]
								},
								"vendor_name": "tensorflow"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "TensorFlow is an open source platform for machine learning. When converting transposed convolutions using per-channel weight quantization the converter segfaults and crashes the Python process. We have patched the issue in GitHub commit aa0b852a4588cea4d36b74feb05d93055540b450. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue."
						}
					]
				},
				"impact": {
					"cvss": {
						"attackComplexity": "HIGH",
						"attackVector": "NETWORK",
						"availabilityImpact": "HIGH",
						"baseScore": 5.9,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					}
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "CWE-20: Improper Input Validation"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-79h2-q768-fpxr",
							"refsource": "CONFIRM",
							"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-79h2-q768-fpxr"
						},
						{
							"name": "https://github.com/tensorflow/tensorflow/issues/53767",
							"refsource": "MISC",
							"url": "https://github.com/tensorflow/tensorflow/issues/53767"
						},
						{
							"name": "https://github.com/tensorflow/tensorflow/commit/aa0b852a4588cea4d36b74feb05d93055540b450",
							"refsource": "MISC",
							"url": "https://github.com/tensorflow/tensorflow/commit/aa0b852a4588cea4d36b74feb05d93055540b450"
						}
					]
				},
				"source": {
					"advisory": "GHSA-79h2-q768-fpxr",
					"discovery": "UNKNOWN"
				}
			}
		}
	}
}
