{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"assignerOrgId": "92fb86c3-55a5-4fb5-9c3f-4757b9e96dc5",
		"assignerShortName": "fedora",
		"cveId": "CVE-2021-43313",
		"datePublished": "2023-03-24T00:00:00",
		"dateReserved": "2021-11-03T00:00:00",
		"dateUpdated": "2023-03-24T00:00:00",
		"state": "PUBLISHED"
	},
	"containers": {
		"cna": {
			"affected": [
				{
					"product": "upx",
					"vendor": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "upx before 4.0.0-git-c6b9e3c62d15"
						}
					]
				}
			],
			"descriptions": [
				{
					"lang": "en",
					"value": "A heap-based buffer overflow was discovered in upx, during the variable 'bucket' points to an inaccessible address. The issue is being triggered in the function PackLinuxElf32::invert_pt_dynamic at p_lx_elf.cpp:1688."
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"cweid": "CWE-119",
							"description": "CWE-119",
							"lang": "en",
							"type": "CWE"
						}
					]
				}
			],
			"providerMetadata": {
				"dateUpdated": "2023-03-24T00:00:00",
				"orgId": "92fb86c3-55a5-4fb5-9c3f-4757b9e96dc5",
				"shortName": "fedora"
			},
			"references": [
				{
					"url": "https://github.com/upx/upx/issues/378"
				}
			]
		}
	}
}
