{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"cveId": "CVE-2021-33840",
		"assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
		"assignerShortName": "mitre",
		"state": "PUBLISHED",
		"datePublished": "2021-06-03T23:57:32",
		"dateUpdated": "2021-06-03T23:57:32",
		"dateReserved": "2021-06-03T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
				"shortName": "mitre",
				"dateUpdated": "2021-06-03T23:57:32"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "The server in Luca through 1.1.14 allows remote attackers to cause a denial of service (insertion of many fake records related to COVID-19) because Phone Number data lacks a digital signature."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://luca-app.de/securityoverview/processes/guest_registration.html#verifying-the-contact-data"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://gitlab.com/lucaapp/web/-/issues/1#note_560963608"
				}
			],
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "cve@mitre.org",
					"ID": "CVE-2021-33840",
					"STATE": "PUBLIC"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "n/a",
											"version": {
												"version_data": [
													{
														"version_value": "n/a"
													}
												]
											}
										}
									]
								},
								"vendor_name": "n/a"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "The server in Luca through 1.1.14 allows remote attackers to cause a denial of service (insertion of many fake records related to COVID-19) because Phone Number data lacks a digital signature."
						}
					]
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "n/a"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "https://luca-app.de/securityoverview/processes/guest_registration.html#verifying-the-contact-data",
							"refsource": "MISC",
							"url": "https://luca-app.de/securityoverview/processes/guest_registration.html#verifying-the-contact-data"
						},
						{
							"name": "https://gitlab.com/lucaapp/web/-/issues/1#note_560963608",
							"refsource": "MISC",
							"url": "https://gitlab.com/lucaapp/web/-/issues/1#note_560963608"
						}
					]
				}
			}
		}
	}
}
