{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"cveId": "CVE-2013-4346",
		"assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
		"assignerShortName": "redhat",
		"state": "PUBLISHED",
		"datePublished": "2014-05-20T14:00:00",
		"dateUpdated": "2016-11-25T19:57:01",
		"dateReserved": "2013-06-12T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "53f830b8-0a3f-465b-8143-3b8a9948e749",
				"shortName": "redhat",
				"dateUpdated": "2016-11-25T19:57:01"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "The Server.verify_request function in SimpleGeo python-oauth2 does not check the nonce, which allows remote attackers to perform replay attacks via a signed URL."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"name": "62386",
					"tags": [
						"vdb-entry",
						"x_refsource_BID"
					],
					"url": "http://www.securityfocus.com/bid/62386"
				},
				{
					"name": "[oss-security] 20130912 Re: cve requests for python-oauth2",
					"tags": [
						"mailing-list",
						"x_refsource_MLIST"
					],
					"url": "http://www.openwall.com/lists/oss-security/2013/09/12/7"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/simplegeo/python-oauth2/issues/129"
				}
			],
			"datePublic": "2013-02-04T00:00:00"
		}
	}
}
