{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2013-7338",
		"assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
		"assignerShortName": "mitre",
		"state": "PUBLISHED",
		"datePublished": "2014-04-22T14:00:00",
		"dateUpdated": "2024-08-06T18:01:20.402Z",
		"dateReserved": "2014-03-18T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
				"shortName": "mitre",
				"dateUpdated": "2017-06-30T16:57:01"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "Python before 3.3.4 RC1 allows remote attackers to cause a denial of service (infinite loop and CPU consumption) via a file size value larger than the size of the zip file to the (1) ZipExtFile.read, (2) ZipExtFile.read(n), (3) ZipExtFile.readlines, (4) ZipFile.extract, or (5) ZipFile.extractall function."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"name": "[oss-security] 20140318 CVE request for python/zipfile",
					"tags": [
						"mailing-list",
						"x_refsource_MLIST"
					],
					"url": "http://seclists.org/oss-sec/2014/q1/592"
				},
				{
					"name": "65179",
					"tags": [
						"vdb-entry",
						"x_refsource_BID"
					],
					"url": "http://www.securityfocus.com/bid/65179"
				},
				{
					"name": "openSUSE-SU-2014:0597",
					"tags": [
						"vendor-advisory",
						"x_refsource_SUSE"
					],
					"url": "http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "http://hg.python.org/cpython/rev/79ea4ce431b1"
				},
				{
					"name": "GLSA-201503-10",
					"tags": [
						"vendor-advisory",
						"x_refsource_GENTOO"
					],
					"url": "https://security.gentoo.org/glsa/201503-10"
				},
				{
					"name": "APPLE-SA-2015-08-13-2",
					"tags": [
						"vendor-advisory",
						"x_refsource_APPLE"
					],
					"url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "http://bugs.python.org/issue20078"
				},
				{
					"name": "[oss-security] 20140319 Re: CVE request for python/zipfile",
					"tags": [
						"mailing-list",
						"x_refsource_MLIST"
					],
					"url": "http://seclists.org/oss-sec/2014/q1/595"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://support.apple.com/kb/HT205031"
				},
				{
					"name": "1029973",
					"tags": [
						"vdb-entry",
						"x_refsource_SECTRACK"
					],
					"url": "http://www.securitytracker.com/id/1029973"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://docs.python.org/3.3/whatsnew/changelog.html"
				}
			],
			"datePublic": "2013-12-27T00:00:00",
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "cve@mitre.org",
					"ID": "CVE-2013-7338",
					"STATE": "PUBLIC"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "n/a",
											"version": {
												"version_data": [
													{
														"version_value": "n/a"
													}
												]
											}
										}
									]
								},
								"vendor_name": "n/a"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "Python before 3.3.4 RC1 allows remote attackers to cause a denial of service (infinite loop and CPU consumption) via a file size value larger than the size of the zip file to the (1) ZipExtFile.read, (2) ZipExtFile.read(n), (3) ZipExtFile.readlines, (4) ZipFile.extract, or (5) ZipFile.extractall function."
						}
					]
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "n/a"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "[oss-security] 20140318 CVE request for python/zipfile",
							"refsource": "MLIST",
							"url": "http://seclists.org/oss-sec/2014/q1/592"
						},
						{
							"name": "65179",
							"refsource": "BID",
							"url": "http://www.securityfocus.com/bid/65179"
						},
						{
							"name": "openSUSE-SU-2014:0597",
							"refsource": "SUSE",
							"url": "http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html"
						},
						{
							"name": "http://hg.python.org/cpython/rev/79ea4ce431b1",
							"refsource": "CONFIRM",
							"url": "http://hg.python.org/cpython/rev/79ea4ce431b1"
						},
						{
							"name": "GLSA-201503-10",
							"refsource": "GENTOO",
							"url": "https://security.gentoo.org/glsa/201503-10"
						},
						{
							"name": "APPLE-SA-2015-08-13-2",
							"refsource": "APPLE",
							"url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html"
						},
						{
							"name": "http://bugs.python.org/issue20078",
							"refsource": "CONFIRM",
							"url": "http://bugs.python.org/issue20078"
						},
						{
							"name": "[oss-security] 20140319 Re: CVE request for python/zipfile",
							"refsource": "MLIST",
							"url": "http://seclists.org/oss-sec/2014/q1/595"
						},
						{
							"name": "https://support.apple.com/kb/HT205031",
							"refsource": "CONFIRM",
							"url": "https://support.apple.com/kb/HT205031"
						},
						{
							"name": "1029973",
							"refsource": "SECTRACK",
							"url": "http://www.securitytracker.com/id/1029973"
						},
						{
							"name": "https://docs.python.org/3.3/whatsnew/changelog.html",
							"refsource": "CONFIRM",
							"url": "https://docs.python.org/3.3/whatsnew/changelog.html"
						}
					]
				}
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-06T18:01:20.402Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"name": "[oss-security] 20140318 CVE request for python/zipfile",
						"tags": [
							"mailing-list",
							"x_refsource_MLIST",
							"x_transferred"
						],
						"url": "http://seclists.org/oss-sec/2014/q1/592"
					},
					{
						"name": "65179",
						"tags": [
							"vdb-entry",
							"x_refsource_BID",
							"x_transferred"
						],
						"url": "http://www.securityfocus.com/bid/65179"
					},
					{
						"name": "openSUSE-SU-2014:0597",
						"tags": [
							"vendor-advisory",
							"x_refsource_SUSE",
							"x_transferred"
						],
						"url": "http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "http://hg.python.org/cpython/rev/79ea4ce431b1"
					},
					{
						"name": "GLSA-201503-10",
						"tags": [
							"vendor-advisory",
							"x_refsource_GENTOO",
							"x_transferred"
						],
						"url": "https://security.gentoo.org/glsa/201503-10"
					},
					{
						"name": "APPLE-SA-2015-08-13-2",
						"tags": [
							"vendor-advisory",
							"x_refsource_APPLE",
							"x_transferred"
						],
						"url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "http://bugs.python.org/issue20078"
					},
					{
						"name": "[oss-security] 20140319 Re: CVE request for python/zipfile",
						"tags": [
							"mailing-list",
							"x_refsource_MLIST",
							"x_transferred"
						],
						"url": "http://seclists.org/oss-sec/2014/q1/595"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://support.apple.com/kb/HT205031"
					},
					{
						"name": "1029973",
						"tags": [
							"vdb-entry",
							"x_refsource_SECTRACK",
							"x_transferred"
						],
						"url": "http://www.securitytracker.com/id/1029973"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://docs.python.org/3.3/whatsnew/changelog.html"
					}
				]
			}
		]
	}
}
